# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cad59fb03cf0f1542dcf1da41dc973c818e9f466ca2b0162c13c5fa059da0a69b94d427a99c9fa4fad71d9bd714ff6dd3d0fab2803b2b4a50b2f7e67802b63e9

test:
  secret_key_base: 2afaaeb420e7f9588e06cb7abb3efac5ae33a2c109a905a48c86c9d31f51a37190e6eedbf701d6d3dc8c875f52cf53eef486c58f617e0c73be415be46143794e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
